# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'HttpGetResponse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HttpGetResponse
pod 'SwiftyJSON','4.2'
pod 'Alamofire','4.2'

  target 'HttpGetResponseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HttpGetResponseUITests' do
    # Pods for testing
  end

end
